version: "3.3"

services:
  hadoop-master:
    image: virtuslab/hadoop:1.0
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "8088:8088"
      - "50070:50070"
      - "23:22"
    networks:
      - "hadoop"
    command: "/root/bootstrap.sh -d -namenode"
  hadoop-slave1:
    image: virtuslab/hadoop:1.0
    container_name: hadoop-slave1
    links:
      - "hadoop-master:hadoop-master"
    ports:
      - "8042:8042"
    networks:
      - "hadoop"
    hostname: hadoop-slave1
    command: "/root/bootstrap.sh -d -datanode"
  hadoop-slave2:
    image: virtuslab/hadoop:1.0
    container_name: hadoop-slave2
    links:
      - "hadoop-master:hadoop-master"
    ports:
      - "8043:8042"
    networks:
        - "hadoop"
    hostname: hadoop-slave2
    command: "/root/bootstrap.sh -d -datanode"

networks:
  hadoop:
    driver: bridge